M48
; DRILL file {KiCad 6.0.7-1.fc36} date Sat 13 Aug 2022 19:35:50 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-13T19:35:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-1.fc36
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X31.5Y-26.5
X31.5Y-76.0
X89.5Y-26.5
X89.5Y-76.0
X124.5Y-26.5
X124.5Y-76.0
T0
M30
